#ifndef INTERFACE_VARIABLES_H_INCLUDED
#define INTERFACE_VARIABLES_H_INCLUDED
const int ORIGINAL_WINDOWS_WIDTH=1100;
const int ORIGINAL_WINDOWS_HEIGHT=1050;
int WINDOWS_WIDTH=ORIGINAL_WINDOWS_WIDTH;
int WINDOWS_HEIGHT=ORIGINAL_WINDOWS_HEIGHT;
#endif //INTERFACE_VARIABLES_H_INCLUDED
